### ISSUE TITLE
Subscriptions cancellation Customer Feedback

### ISSUE THREAD

**Issue by TomasHurtz** [Prospress/woocommerce-subscriptions-renewal-logger#1]
Hi

Sorry if this is the wrorg place to ask this (not sure where to ask) but would it be possible to require a reason from the customer when they cancel their subscription?

**Comment by james-allan** [comment]
Hi @TomasHurtz. 

Yeah this isn't the right place to ask these type of questions about the Subscriptions plugin. In future, if you have these type of questions, please open a support ticket at: https://woocommerce.com/my-account/create-a-ticket or get in contact with us at https://prospress.com/support/.

In regards to your question, there isn't any way to achieve this with the Subscriptions plugin out of the box. If you would like to suggest this as a feature, I would encourage you to submit this or any feature request you have to Ideas Board. You can find it here: http://ideas.woocommerce.com/forums/133476-woocommerce?category_id=146472

If you're looking for a more short-term fix you could try a third-party solution like [AutomateWoo](https://automatewoo.com/) to send feedback request emails after subscription cancellations. Alternatively, you could get in contact with a developer who may be able to write some custom code for you to achieve this.

I'm going to close this issue but if you have further questions please get in contact with us via those links I mentioned above.
